export const SHARE_URL_WARNING_LENGTH = 4000
export const SHARE_URL_MAX_LENGTH = 12000
export const SHARE_ENCODED_TOKEN_MAX_LENGTH = SHARE_URL_MAX_LENGTH
export const SHARE_DECODED_JSON_MAX_LENGTH = 100 * 1024
// UTF-8 uses at most three bytes per JavaScript UTF-16 code unit.
export const SHARE_DECOMPRESSED_BYTES_MAX_LENGTH =
  SHARE_DECODED_JSON_MAX_LENGTH * 3
export const SHARE_SOURCE_CODE_MAX_LENGTH = 64 * 1024
export const SHARE_INPUT_JSON_MAX_LENGTH = 32 * 1024
