/** Playback timing and slider bounds for algorithm execution. */
export const EXECUTION_CONSTANTS = {
  EXECUTION_INTERVAL_MS: 100,
  MIN_PLAYBACK_SPEED: 15,
  MAX_PLAYBACK_SPEED: 750,
  PLAYBACK_SLIDER_MIN: 0,
  PLAYBACK_SLIDER_MAX: 1000,
  PLAYBACK_SLIDER_CENTER: 500,
  PLAYBACK_SLIDER_STEP: 5,
  PLAYBACK_RESTART_DELAY_MS: 0,
} as const
